spring:
  mail:
    host: smtp.qq.com
    port: 587
    username: 1458881379@qq.com
    password: iwibipzwhfsnhgeh
    properties:
      mail:
        debug: true
        smtp:
          starttls:
            enable: true
          auth: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        ssl:
          enable: true
          protocols: TLSv1.2
    default-encoding: utf-8
    name: kirito
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
#    properties:
#      mail:
#        smtp:
#          ssl:
#            enable: true
