spring:
  application:
    name: supermall-gateway



  cloud:
    nacos:
      config:
        import-check:
          enabled: false


    gateway:
      routes:
        - id: query_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu


        - id: qq-route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        - id: product-route
          uri: lb://supermall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: admin-route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}



server:
  port: 88
