spring:
  application:
    name: supermall-gateway



  cloud:
    nacos:
      config:
        import-check:
          enabled: false


    gateway:
      routes:
        - id: query_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu


        - id: qq-route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        - id: product-route
          uri: lb://supermall-product
          predicates:
            - Path=/api/product/**, /hello
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: third-party
          uri: lb://supermall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/?(?<segment>.*), /$\{segment}

        - id: member-route
          uri: lb://supermall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: ware-route
          uri: lb://supermall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: admin-route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}

        - id: supermall-host-route
          uri: lb://supermall-product
          predicates:
            - Host=supermall00.com,item.supermall00.com

        - id: supermall-search-route
          uri: lb://supermall-search
          predicates:
            - Host=search.supermall00.com

        - id: supermall-auth-route
          uri: lb://supermall-auth-server
          predicates:
            - Host=auth.supermall00.com


server:
  port: 88
