spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/supermall_ums
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: supermall-member

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000
